from typing import List, Optional
from pydantic import BaseModel, Field


class CrossSellPerformanceItem(BaseModel):
    trigger_category: str = Field(..., description="Category that triggers the cross-sell rule")
    recommend_category: str = Field(..., description="Category recommended by the policy rule")
    matches_count: int = Field(..., description="Number of confirmed orders containing both categories")


class ChannelPerformanceItem(BaseModel):
    channel: str = Field(..., description="Machine-readable channel key: direct_storefront | in_app_agent | external_ai")
    channel_label: str = Field(..., description="Human-readable channel name")
    orders_count: int = Field(..., description="Count of confirmed orders attributed to this channel")
    revenue_paise: int = Field(..., description="Total revenue generated by this channel in paise")
    revenue_inr: float = Field(..., description="Total revenue generated by this channel in INR")
    share_percentage: float = Field(..., description="Percentage share of total gross revenue")


class DailyTrendItem(BaseModel):
    date: str = Field(..., description="Date formatted as YYYY-MM-DD")
    orders_count: int = Field(..., description="Confirmed orders placed on this date")
    revenue_inr: float = Field(..., description="Revenue in INR generated on this date")
    ai_sessions_count: int = Field(..., description="Active AI sessions recorded on this date")


class AdminAnalyticsResponse(BaseModel):
    # Topline KPIs
    gross_revenue_paise: int = Field(..., description="Total gross revenue from confirmed orders in paise")
    gross_revenue_inr: float = Field(..., description="Total gross revenue from confirmed orders in INR")
    confirmed_orders_count: int = Field(..., description="Total count of confirmed/fulfilled orders")
    active_skus_count: int = Field(..., description="Current count of active SKUs in the catalog")
    aov_paise: int = Field(..., description="Average order value in paise")
    aov_inr: float = Field(..., description="Average order value in INR")

    # Funnel & Carts
    total_carts_created: int = Field(..., description="Total carts created in SQLite")
    carts_with_items_count: int = Field(..., description="Carts that had at least one item added")
    converted_carts_count: int = Field(..., description="Carts that successfully converted into paid orders")
    abandoned_carts_count: int = Field(..., description="Carts with items that have not converted")
    cart_to_order_conversion_rate: float = Field(..., description="Percentage of carts with items converted to orders")
    overall_conversion_rate: float = Field(..., description="Percentage of total carts converted to orders")

    # AI Conversations & Telemetry
    in_app_agent_turns_count: int = Field(..., description="Total chat turns handled by the in-app agent")
    in_app_agent_sessions_count: int = Field(..., description="Distinct shopper sessions that interacted with the in-app agent")
    external_ai_tool_calls_count: int = Field(..., description="Total MCP tool calls executed by external AI buyers")
    external_ai_sessions_count: int = Field(..., description="Distinct sessions driven by external AI buyers via MCP")
    total_ai_sessions_count: int = Field(..., description="Combined distinct AI sessions across both channels")

    # Cross-Sell Acceptance (Policy Ground Truth)
    cross_sell_eligible_orders_count: int = Field(..., description="Orders containing at least one trigger-category item")
    cross_sell_accepted_orders_count: int = Field(..., description="Orders containing both trigger and recommended category items")
    cross_sell_acceptance_rate: float = Field(..., description="Cross-sell basket attachment rate as a percentage")
    cross_sell_rules_summary: List[CrossSellPerformanceItem] = Field(..., description="Breakdown of cross-sell matches per rule")

    # Channel Attribution & Trends
    channel_breakdown: List[ChannelPerformanceItem] = Field(..., description="Revenue and order performance per channel")
    daily_trends: List[DailyTrendItem] = Field(..., description="Daily trend points for charting")
    days_window: Optional[int] = Field(None, description="Active time window filter in days, or None if all-time")
